# .air.toml
# Air configuration for live-reloading Go server

# Build settings
[build]
# Command to build the server
cmd = "go build -o ./tmp/main ./src/main.go"
# Output binary
bin = "./tmp/main"
# Files extensions to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to ignore
exclude_dir = ["assets", "tmp", "vendor"]
# Enable or disable build cache
build_delay = 1000 # milliseconds

# Logging settings
[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

# Optional: run hooks before/after build
[log]
time = true
