root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./src/main.go"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  build_delay = 1000

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true
