FROM golang:alpine

WORKDIR /usr/src/app
RUN apk --no-cache add curl netcat-openbsd

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the binary with optimizations for production
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /go-app ./src
